export const topicOptions = [
  { title: "Training and Education", desc: "290+ courses" },
  { title: "IT Help Desk", desc: "320+ courses" },
  { title: "Business Analytics and Strategy", desc: "810+ courses" },
  { title: "Career Development", desc: "440+ courses" },
  { title: "Finance and Accounting", desc: "270+ courses" },
  { title: "Leadership and Management", desc: "1,270+ courses" },
  { title: "Mobile Development", desc: "470+ courses" },
  { title: "Marketing", desc: "800+ courses" },
  { title: "Cloud Computing", desc: "910+ courses" },
  { title: "Project Management", desc: "390+ courses" },
  { title: "Visualization and Real-Time", desc: "1,290+ courses" },
  { title: "Animation and Illustration", desc: "1,670+ courses" },
  { title: "Audio and Music", desc: "410+ courses" },
  { title: "AEC", desc: "1,400+ courses" },
  { title: "Graphic Design", desc: "910+ courses" },
  { title: "Motion Grapics and VFX", desc: "900+ courses" },
  { title: "Photography", desc: "1,120+ courses" },
  { title: "Video", desc: "590+ courses" },
  { title: "Data Science", desc: "860+ courses" },
  { title: "Network and System Administration", desc: "1,230+ courses" },
  { title: "Software Development", desc: "1,900+ courses" },
  { title: "User Experience", desc: "490+ courses" },
  { title: "Web Design", desc: "530+ courses" },
  { title: "Database Management", desc: "310+ courses" },
  { title: "Web Development", desc: "1,340+ courses" },
  { title: "Product and Manufacturing", desc: "1,210+ courses" },
  { title: "Sales", desc: "220+ courses" },
  { title: "Human Resources", desc: "360+ courses" },
  { title: "DevOps", desc: "230+ courses" },
  { title: "Small Business and Enterpreneurship", desc: "320+ courses" },
  { title: "Costumer Service", desc: "170+ courses" },
  { title: "Diversity, Equity, and Inclusion (DEI)", desc: "150+ courses" },
  { title: "Professional Development", desc: "1,250+ courses" },
  { title: "Business Software and Tools", desc: "1,880+ courses" },
  { title: "Security", desc: "620+ courses" },
];
